export const API_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INVARIANT_VIOLATION: "INVARIANT_VIOLATION",
  PAYMENTS_STATE_ERROR: "PAYMENTS_STATE_ERROR",
  OUTBOX_AUTH_ERROR: "OUTBOX_AUTH_ERROR",
  STALE_SESSION: "STALE_SESSION",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ApiErrorCode = typeof API_ERROR_CODES[keyof typeof API_ERROR_CODES];
